apiVersion: v1
kind: Pod
metadata:
    name: redis-master
    namespace: databases
    labels:
        app: redis-master
spec:
    containers:
        - name: redis
          image: redis:1.2.3
          ports:
            - containerPort: 30555
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
    volumes:
        - name: config-volume
          configMap:
            name: redis-config
